# Generated by Django 2.2.5 on 2022-05-06 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rts_forms', '0002_supplier_supplier_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='waste_delivery_note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('department', models.CharField(blank=True, max_length=20)),
                ('material_quantity', models.FloatField(max_length=40, verbose_name='Estimated Quantity')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('items_disposed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rts_forms.Material', verbose_name='Material Description')),
            ],
        ),
    ]
