# Generated by Django 2.2.5 on 2022-05-11 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rts_forms', '0003_auto_20220511_1210'),
        ('waste_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waste_delivery_note',
            name='items_disposed',
        ),
        migrations.RemoveField(
            model_name='waste_delivery_note',
            name='material_quantity',
        ),
        migrations.AddField(
            model_name='waste_delivery_note',
            name='item1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material1', to='rts_forms.Material', verbose_name='Material Description'),
        ),
        migrations.AddField(
            model_name='waste_delivery_note',
            name='item2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material2', to='rts_forms.Material', verbose_name='Material Description'),
        ),
        migrations.AddField(
            model_name='waste_delivery_note',
            name='item3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material3', to='rts_forms.Material', verbose_name='Material Description'),
        ),
        migrations.AddField(
            model_name='waste_delivery_note',
            name='item4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material4', to='rts_forms.Material', verbose_name='Material Description'),
        ),
        migrations.AddField(
            model_name='waste_delivery_note',
            name='item5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material5', to='rts_forms.Material', verbose_name='Material Description'),
        ),
        migrations.AddField(
            model_name='waste_delivery_note',
            name='item_qty1',
            field=models.FloatField(blank=True, max_length=40, null=True, verbose_name='Estimated Quantity'),
        ),
        migrations.AddField(
            model_name='waste_delivery_note',
            name='item_qty2',
            field=models.FloatField(blank=True, max_length=40, null=True, verbose_name='Estimated Quantity'),
        ),
        migrations.AddField(
            model_name='waste_delivery_note',
            name='item_qty3',
            field=models.FloatField(blank=True, max_length=40, null=True, verbose_name='Estimated Quantity'),
        ),
        migrations.AddField(
            model_name='waste_delivery_note',
            name='item_qty4',
            field=models.FloatField(blank=True, max_length=40, null=True, verbose_name='Estimated Quantity'),
        ),
        migrations.AddField(
            model_name='waste_delivery_note',
            name='item_qty5',
            field=models.FloatField(blank=True, max_length=40, null=True, verbose_name='Estimated Quantity'),
        ),
    ]
