# Generated by Django 2.2.5 on 2022-05-12 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rts_forms', '0003_auto_20220511_1210'),
        ('waste_management', '0002_auto_20220511_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste_delivery_note',
            name='item6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material6', to='rts_forms.Material', verbose_name='Material Description'),
        ),
        migrations.AddField(
            model_name='waste_delivery_note',
            name='item7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material7', to='rts_forms.Material', verbose_name='Material Description'),
        ),
        migrations.AddField(
            model_name='waste_delivery_note',
            name='item8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material8', to='rts_forms.Material', verbose_name='Material Description'),
        ),
        migrations.AddField(
            model_name='waste_delivery_note',
            name='item_qty6',
            field=models.FloatField(blank=True, max_length=40, null=True, verbose_name='Estimated Quantity'),
        ),
        migrations.AddField(
            model_name='waste_delivery_note',
            name='item_qty7',
            field=models.FloatField(blank=True, max_length=40, null=True, verbose_name='Estimated Quantity'),
        ),
        migrations.AddField(
            model_name='waste_delivery_note',
            name='item_qty8',
            field=models.FloatField(blank=True, max_length=40, null=True, verbose_name='Estimated Quantity'),
        ),
    ]
