# Generated by Django 2.2.5 on 2022-05-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0003_auto_20220512_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste_delivery_note',
            name='hod_comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='HOD comment'),
        ),
    ]
