# Generated by Django 2.2.5 on 2022-05-17 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0004_waste_delivery_note_hod_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('material_code', models.CharField(max_length=12)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='waste_delivery_note',
            name='item1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material1', to='waste_management.Material', verbose_name='Material Description'),
        ),
        migrations.AlterField(
            model_name='waste_delivery_note',
            name='item2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material2', to='waste_management.Material', verbose_name='Material Description'),
        ),
        migrations.AlterField(
            model_name='waste_delivery_note',
            name='item3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material3', to='waste_management.Material', verbose_name='Material Description'),
        ),
        migrations.AlterField(
            model_name='waste_delivery_note',
            name='item4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material4', to='waste_management.Material', verbose_name='Material Description'),
        ),
        migrations.AlterField(
            model_name='waste_delivery_note',
            name='item5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material5', to='waste_management.Material', verbose_name='Material Description'),
        ),
        migrations.AlterField(
            model_name='waste_delivery_note',
            name='item6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material6', to='waste_management.Material', verbose_name='Material Description'),
        ),
        migrations.AlterField(
            model_name='waste_delivery_note',
            name='item7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material7', to='waste_management.Material', verbose_name='Material Description'),
        ),
        migrations.AlterField(
            model_name='waste_delivery_note',
            name='item8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material8', to='waste_management.Material', verbose_name='Material Description'),
        ),
    ]
