# Generated by Django 2.2.5 on 2022-05-18 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waste_management', '0006_auto_20220517_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste_delivery_note',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Head_of_Department', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waste_delivery_note',
            name='warehouse_hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Warehouse_Head_of_Department', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waste_delivery_note',
            name='warehouse_hod_comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' Warehouse HOD comment'),
        ),
    ]
