# Generated by Django 2.2.5 on 2022-05-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0007_auto_20220518_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste_delivery_note',
            name='waste_offloader',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Acknowledged By'),
        ),
        migrations.AlterField(
            model_name='waste_delivery_note',
            name='waste_loader',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Loaded By'),
        ),
    ]
