# Generated by Django 2.2.5 on 2022-05-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0008_auto_20220518_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste_delivery_note',
            name='warehouse_hod_comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' Warehouse HOD Comment'),
        ),
    ]
