# Generated by Django 2.2.5 on 2022-06-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0010_waste_delivery_note_form_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waste_delivery_note',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='waste_delivery_note',
            name='checklist',
            field=models.BooleanField(default=False),
        ),
    ]
