# Generated by Django 2.2.5 on 2022-07-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0013_checklist_form_serials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='form_serials',
            field=models.IntegerField(blank=True, max_length=100),
        ),
    ]
