# Generated by Django 2.2.5 on 2022-07-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0014_auto_20220708_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='form_serials',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
