# Generated by Django 2.2.5 on 2022-07-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0016_auto_20220725_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='form_status',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
