# Generated by Django 2.2.5 on 2022-08-01 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waste_management', '0018_auto_20220725_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='kgrn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_serials', models.CharField(blank=True, max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('kgrn_status', models.IntegerField(default='0', null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
