# Generated by Django 2.2.5 on 2022-08-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0021_goods_issue_note_isinternal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods_issue_note',
            old_name='department',
            new_name='department_from',
        ),
        migrations.AddField(
            model_name='goods_issue_note',
            name='department_to',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='isInternal',
            field=models.BooleanField(default=False, verbose_name='Internal/External'),
        ),
    ]
