# Generated by Django 2.2.5 on 2022-08-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0022_auto_20220818_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_issue_note',
            name='fm_comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='FM comment'),
        ),
    ]
