# Generated by Django 2.2.5 on 2022-08-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0026_auto_20220824_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty1_sale',
            field=models.FloatField(blank=True, max_length=40, null=True, verbose_name='WB Weight:'),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty2_sale',
            field=models.FloatField(blank=True, max_length=40, null=True, verbose_name='WB Weight:'),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty3_sale',
            field=models.FloatField(blank=True, max_length=40, null=True, verbose_name='WB Weight:'),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty4_sale',
            field=models.FloatField(blank=True, max_length=40, null=True, verbose_name='WB Weight:'),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty5_sale',
            field=models.FloatField(blank=True, max_length=40, null=True, verbose_name='WB Weight:'),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty6_sale',
            field=models.FloatField(blank=True, max_length=40, null=True, verbose_name='WB Weight:'),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty7_sale',
            field=models.FloatField(blank=True, max_length=40, null=True, verbose_name='WB Weight:'),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty8_sale',
            field=models.FloatField(blank=True, max_length=40, null=True, verbose_name='WB Weight:'),
        ),
    ]
