# Generated by Django 2.2.5 on 2022-08-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0027_auto_20220831_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='uom',
            field=models.CharField(blank=True, default='PC', max_length=20, null=True, verbose_name='UOM'),
        ),
    ]
