# Generated by Django 2.2.5 on 2022-08-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0028_material_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Price'),
        ),
    ]
