# Generated by Django 3.2.14 on 2022-09-16 15:46

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0029_material_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_issue_note',
            name='my_total',
            field=computed_property.fields.ComputedIntegerField(blank=True, compute_from='double_it', editable=False, null=True, verbose_name='Total'),
        ),
    ]
