# Generated by Django 3.2.14 on 2022-09-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0034_alter_goods_issue_note_item_qty2_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty1_sale',
            field=models.FloatField(blank=True, max_length=5, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty2_sale',
            field=models.FloatField(blank=True, max_length=5, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty3_sale',
            field=models.FloatField(blank=True, max_length=5, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty4_sale',
            field=models.FloatField(blank=True, max_length=5, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty5_sale',
            field=models.FloatField(blank=True, max_length=5, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty6_sale',
            field=models.FloatField(blank=True, max_length=5, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty7_sale',
            field=models.FloatField(blank=True, max_length=5, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty8_sale',
            field=models.FloatField(blank=True, max_length=5, null=True, verbose_name=''),
        ),
    ]
