# Generated by Django 3.2.14 on 2022-09-19 11:06

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0035_auto_20220916_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_issue_note',
            name='my_total',
            field=computed_property.fields.ComputedFloatField(blank=True, compute_from='get_cost', editable=False, null=True, verbose_name='Total'),
        ),
    ]
