# Generated by Django 3.2.14 on 2022-09-19 11:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waste_management', '0037_rename_goods_issue_note_goods_issue_note1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='goods_issue_note1',
            new_name='goods_issue_note',
        ),
    ]
