# Generated by Django 3.2.14 on 2022-09-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0039_auto_20220919_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_issue_note',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
