# Generated by Django 4.1.1 on 2022-09-19 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("waste_management", "0040_alter_goods_issue_note_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goods_issue_note",
            name="my_total",
        ),
    ]
