# Generated by Django 4.1.1 on 2022-09-19 15:49

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("waste_management", "0041_remove_goods_issue_note_my_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods_issue_note",
            name="my_total",
            field=computed_property.fields.ComputedFloatField(
                compute_from="get_cost",
                default="0",
                editable=False,
                null=True,
                verbose_name="Total",
            ),
        ),
    ]
