# Generated by Django 4.1.1 on 2022-09-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waste_management", "0042_goods_issue_note_my_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods_issue_note",
            name="my_total",
            field=models.FloatField(
                blank=True, max_length=40, null=True, verbose_name="Total"
            ),
        ),
    ]
