# Generated by Django 4.1.1 on 2022-09-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waste_management", "0044_alter_goods_issue_note_item_qty1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods_issue_note",
            name="my_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Total",
            ),
        ),
    ]
