# Generated by Django 3.2.14 on 2022-09-20 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waste_management', '0046_auto_20220920_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='kgrn',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='H_O_D', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kgrn',
            name='hod_comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Head Of Dept comment'),
        ),
    ]
