# Generated by Django 3.2.14 on 2022-09-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0047_auto_20220920_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_issue_note',
            name='gross_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Gross Total'),
        ),
    ]
