# Generated by Django 3.2.14 on 2022-09-21 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waste_management', '0048_goods_issue_note_gross_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_issue_note',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='HOD', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goods_issue_note',
            name='hod_comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='HOD comment'),
        ),
    ]
