# Generated by Django 3.2.14 on 2022-09-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0050_auto_20220921_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_issue_note',
            name='item_qty1_wh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Warehouse Weight'),
        ),
        migrations.AddField(
            model_name='goods_issue_note',
            name='item_qty2_wh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Warehouse Weight'),
        ),
        migrations.AddField(
            model_name='goods_issue_note',
            name='item_qty3_wh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Warehouse Weight'),
        ),
        migrations.AddField(
            model_name='goods_issue_note',
            name='item_qty4_wh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Warehouse Weight'),
        ),
        migrations.AddField(
            model_name='goods_issue_note',
            name='item_qty5_wh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Warehouse Weight'),
        ),
        migrations.AddField(
            model_name='goods_issue_note',
            name='item_qty6_wh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Warehouse Weight'),
        ),
        migrations.AddField(
            model_name='goods_issue_note',
            name='item_qty7_wh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Warehouse Weight'),
        ),
        migrations.AddField(
            model_name='goods_issue_note',
            name='item_qty8_wh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Warehouse Weight'),
        ),
    ]
