# Generated by Django 3.2.14 on 2022-09-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0051_auto_20220923_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Estimated Quantity'),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty1_wh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Warehouse Weight'),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Estimated Quantity'),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty2_wh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Warehouse Weight'),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Estimated Quantity'),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty3_wh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Warehouse Weight'),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Estimated Quantity'),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty4_wh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Warehouse Weight'),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Estimated Quantity'),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty5_wh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Warehouse Weight'),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Estimated Quantity'),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty6_wh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Warehouse Weight'),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty7',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Estimated Quantity'),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty7_wh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Warehouse Weight'),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty8',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Estimated Quantity'),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='item_qty8_wh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Warehouse Weight'),
        ),
    ]
