# Generated by Django 3.2.14 on 2022-09-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0053_goods_issue_note_total_weight_wh'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_issue_note',
            name='total_weight_wb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total WB Weight'),
        ),
    ]
