# Generated by Django 3.2.14 on 2022-09-24 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waste_management', '0054_goods_issue_note_total_weight_wb'),
    ]

    operations = [
        migrations.AddField(
            model_name='kgrn',
            name='purchase_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Purchasing_Rep', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='total_weight_wb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name=''),
        ),
    ]
