# Generated by Django 3.2.14 on 2022-09-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0055_auto_20220924_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='kgrn',
            name='department',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
