# Generated by Django 3.2.14 on 2022-09-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0056_kgrn_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='kgrn',
            name='purchase_comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Purchase comment'),
        ),
    ]
