# Generated by Django 3.2.14 on 2022-09-30 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0057_kgrn_purchase_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('department_code', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='goods_issue_note',
            name='department_internal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Department_Internal', to='waste_management.department'),
        ),
    ]
