# Generated by Django 3.2.14 on 2022-10-05 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waste_management', '0059_kgrn_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='kgrn_item',
            name='purchase_comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Purchasing comment'),
        ),
        migrations.AddField(
            model_name='kgrn_item',
            name='purchase_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Purchasing_Representative', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kgrn_item',
            name='item_qty1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Estimated Quantity'),
        ),
        migrations.AlterField(
            model_name='kgrn_item',
            name='item_qty2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Estimated Quantity'),
        ),
        migrations.AlterField(
            model_name='kgrn_item',
            name='item_qty3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Estimated Quantity'),
        ),
        migrations.AlterField(
            model_name='kgrn_item',
            name='item_qty4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Estimated Quantity'),
        ),
        migrations.AlterField(
            model_name='kgrn_item',
            name='item_qty5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Estimated Quantity'),
        ),
        migrations.AlterField(
            model_name='kgrn_item',
            name='item_qty6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Estimated Quantity'),
        ),
        migrations.AlterField(
            model_name='kgrn_item',
            name='item_qty7',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Estimated Quantity'),
        ),
        migrations.AlterField(
            model_name='kgrn_item',
            name='item_qty8',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Estimated Quantity'),
        ),
    ]
