# Generated by Django 3.2.14 on 2022-10-06 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0060_auto_20221005_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='kgrn_item',
            name='resolution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='waste_management.resolve'),
        ),
    ]
