# Generated by Django 3.2.14 on 2022-10-06 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0061_auto_20221006_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kgrn_item',
            name='resolution',
        ),
        migrations.AddField(
            model_name='kgrn_item',
            name='resolution1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolution1', to='waste_management.resolve'),
        ),
        migrations.AddField(
            model_name='kgrn_item',
            name='resolution2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolution2', to='waste_management.resolve'),
        ),
        migrations.AddField(
            model_name='kgrn_item',
            name='resolution3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolution3', to='waste_management.resolve'),
        ),
        migrations.AddField(
            model_name='kgrn_item',
            name='resolution4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolution4', to='waste_management.resolve'),
        ),
        migrations.AddField(
            model_name='kgrn_item',
            name='resolution5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolution5', to='waste_management.resolve'),
        ),
        migrations.AddField(
            model_name='kgrn_item',
            name='resolution6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolution6', to='waste_management.resolve'),
        ),
        migrations.AddField(
            model_name='kgrn_item',
            name='resolution7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolution7', to='waste_management.resolve'),
        ),
        migrations.AddField(
            model_name='kgrn_item',
            name='resolution8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolution8', to='waste_management.resolve'),
        ),
    ]
