# Generated by Django 3.2.14 on 2022-10-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0063_auto_20221006_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_issue_note',
            name='department_to',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
