# Generated by Django 3.2.14 on 2022-10-17 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0065_auto_20221017_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kgrn_item',
            name='reason1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reason1', to='waste_management.reason', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='kgrn_item',
            name='reason2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reason2', to='waste_management.reason', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='kgrn_item',
            name='reason3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reason3', to='waste_management.reason', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='kgrn_item',
            name='reason4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reason4', to='waste_management.reason', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='kgrn_item',
            name='reason5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reason5', to='waste_management.reason', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='kgrn_item',
            name='reason6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reason6', to='waste_management.reason', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='kgrn_item',
            name='reason7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reason7', to='waste_management.reason', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='kgrn_item',
            name='reason8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reason8', to='waste_management.reason', verbose_name=''),
        ),
    ]
