# Generated by Django 3.2.14 on 2022-10-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0066_auto_20221017_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='kgrn',
            name='serial_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kgrn_item',
            name='serial_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
