# Generated by Django 3.2.14 on 2022-10-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0068_kgrn_item_closed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='kgrn_item',
            name='accounts_comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Accounts comment'),
        ),
    ]
