# Generated by Django 3.2.14 on 2022-10-21 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waste_management', '0069_kgrn_item_accounts_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='kgrn',
            name='accounts_comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Accounts comments'),
        ),
        migrations.AddField(
            model_name='kgrn',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Accounts_Rep', to=settings.AUTH_USER_MODEL),
        ),
    ]
