# Generated by Django 3.2.14 on 2022-10-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0070_auto_20221021_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='kgrn',
            name='collected_by',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Collected By'),
        ),
        migrations.AddField(
            model_name='kgrn',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID Number'),
        ),
        migrations.AddField(
            model_name='kgrn',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Vehicle No'),
        ),
        migrations.AlterField(
            model_name='goods_issue_note',
            name='fm_comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='kgrn',
            name='kgrn_status',
            field=models.IntegerField(default='0.5', null=True),
        ),
    ]
