# Generated by Django 3.2.14 on 2022-10-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0071_auto_20221024_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kgrn',
            name='kgrn_status',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
