# Generated by Django 3.2.14 on 2022-11-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0074_kgrn_pur_close_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='kgrn_item',
            name='pur_close_comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Procurement closing comment'),
        ),
    ]
