# Generated by Django 3.2.14 on 2022-11-01 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0075_kgrn_item_pur_close_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('customer_code', models.CharField(max_length=40, null=True)),
                ('mobile_number1', models.IntegerField(default='0', null=True)),
                ('mobile_number2', models.IntegerField(default='0', null=True)),
                ('refered_by', models.CharField(blank=True, max_length=40, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=40, null=True)),
                ('material1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item1', to='waste_management.material', verbose_name='Material Description')),
                ('material2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item2', to='waste_management.material', verbose_name='Material Description')),
                ('material3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item3', to='waste_management.material', verbose_name='Material Description')),
                ('material4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item4', to='waste_management.material', verbose_name='Material Description')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='goods_issue_note',
            name='department_to1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Department_to', to='waste_management.customer'),
        ),
    ]
