# Generated by Django 3.2.14 on 2022-11-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0078_rename_department_to1_goods_issue_note_department_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_issue_note',
            name='received_by',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Received By'),
        ),
    ]
