# Generated by Django 4.1.3 on 2023-01-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("waste_management", "0082_alter_kgrn_department_alter_kgrn_supplier"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goods_issue_note",
            old_name="isInternal",
            new_name="isinternal",
        ),
    ]
