# Generated by Django 4.1.3 on 2023-03-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waste_management", "0084_alter_department_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kgrn",
            name="serial_num",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="kgrn_item",
            name="serial_num",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
