# Generated by Django 4.2.1 on 2023-07-26 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0086_rename_goods_issue_note_goodsissuenote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item1',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item2',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item3',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item4',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item5',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item6',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item7',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item8',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item_qty1',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item_qty1_sale',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item_qty1_wh',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item_qty2',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item_qty2_sale',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item_qty2_wh',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item_qty3',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item_qty3_sale',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item_qty3_wh',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item_qty4',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item_qty4_sale',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item_qty4_wh',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item_qty5',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item_qty5_sale',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item_qty5_wh',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item_qty6',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item_qty6_sale',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item_qty6_wh',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item_qty7',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item_qty7_sale',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item_qty7_wh',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item_qty8',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item_qty8_sale',
        ),
        migrations.RemoveField(
            model_name='goodsissuenote',
            name='item_qty8_wh',
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='material_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_issue_notes_1', to='waste_management.material', verbose_name='Material 1 Description'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='material_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_issue_notes_2', to='waste_management.material', verbose_name='Material 2 Description'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='material_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_issue_notes_3', to='waste_management.material', verbose_name='Material 3 Description'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='material_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_issue_notes_4', to='waste_management.material', verbose_name='Material 4 Description'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='material_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_issue_notes_5', to='waste_management.material', verbose_name='Material 5 Description'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='material_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_issue_notes_6', to='waste_management.material', verbose_name='Material 6 Description'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='material_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_issue_notes_7', to='waste_management.material', verbose_name='Material 7 Description'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='material_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_issue_notes_8', to='waste_management.material', verbose_name='Material 8 Description'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='material_quantity_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material 1 Estimated Quantity'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='material_quantity_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material 2 Estimated Quantity'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='material_quantity_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material 3 Estimated Quantity'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='material_quantity_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material 4 Estimated Quantity'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='material_quantity_5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material 5 Estimated Quantity'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='material_quantity_6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material 6 Estimated Quantity'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='material_quantity_7',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material 7 Estimated Quantity'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='material_quantity_8',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material 8 Estimated Quantity'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='warehouse_weight_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material 1 Warehouse Weight'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='warehouse_weight_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material 2 Warehouse Weight'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='warehouse_weight_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material 3 Warehouse Weight'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='warehouse_weight_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material 4 Warehouse Weight'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='warehouse_weight_5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material 5 Warehouse Weight'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='warehouse_weight_6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material 6 Warehouse Weight'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='warehouse_weight_7',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material 7 Warehouse Weight'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='warehouse_weight_8',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material 8 Warehouse Weight'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='weighbridge_weight_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Material 1 Weighbridge Weight'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='weighbridge_weight_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Material 2 Weighbridge Weight'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='weighbridge_weight_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Material 3 Weighbridge Weight'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='weighbridge_weight_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Material 4 Weighbridge Weight'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='weighbridge_weight_5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Material 5 Weighbridge Weight'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='weighbridge_weight_6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Material 6 Weighbridge Weight'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='weighbridge_weight_7',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Material 7 Weighbridge Weight'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='weighbridge_weight_8',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Material 8 Weighbridge Weight'),
        ),
    ]
