# Generated by Django 4.2.1 on 2023-07-28 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0087_remove_goodsissuenote_item1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsissuenote',
            name='material_10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_issue_notes_10', to='waste_management.material', verbose_name='Material 10 Description'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='material_11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_issue_notes_11', to='waste_management.material', verbose_name='Material 11 Description'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='material_12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_issue_notes_12', to='waste_management.material', verbose_name='Material 12 Description'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='material_13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_issue_notes_13', to='waste_management.material', verbose_name='Material 13 Description'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='material_14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_issue_notes_14', to='waste_management.material', verbose_name='Material 14 Description'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='material_15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_issue_notes_15', to='waste_management.material', verbose_name='Material 15 Description'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='material_9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_issue_notes_9', to='waste_management.material', verbose_name='Material 9 Description'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='material_quantity_10',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material 10 Estimated Quantity'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='material_quantity_11',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material 11 Estimated Quantity'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='material_quantity_12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material 12 Estimated Quantity'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='material_quantity_13',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material 13 Estimated Quantity'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='material_quantity_14',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material 14 Estimated Quantity'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='material_quantity_15',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material 15 Estimated Quantity'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='material_quantity_9',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material 9 Estimated Quantity'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='warehouse_weight_10',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material 10 Warehouse Weight'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='warehouse_weight_11',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material 11 Warehouse Weight'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='warehouse_weight_12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material 12 Warehouse Weight'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='warehouse_weight_13',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material 13 Warehouse Weight'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='warehouse_weight_14',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material 14 Warehouse Weight'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='warehouse_weight_15',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material 15 Warehouse Weight'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='warehouse_weight_9',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Material 9 Warehouse Weight'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='weighbridge_weight_10',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Material 10 Weighbridge Weight'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='weighbridge_weight_11',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Material 11 Weighbridge Weight'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='weighbridge_weight_12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Material 12 Weighbridge Weight'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='weighbridge_weight_13',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Material 13 Weighbridge Weight'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='weighbridge_weight_14',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Material 14 Weighbridge Weight'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='weighbridge_weight_15',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Material 15 Weighbridge Weight'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='weighbridge_weight_9',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Material 9 Weighbridge Weight'),
        ),
    ]
