# Generated by Django 4.2.5 on 2023-10-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waste_management", "0090_alter_goodsissuenote_weighbridge_weight_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsissuenote",
            name="weighbridge_weight_1",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True, verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="goodsissuenote",
            name="weighbridge_weight_10",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True, verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="goodsissuenote",
            name="weighbridge_weight_11",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True, verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="goodsissuenote",
            name="weighbridge_weight_12",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True, verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="goodsissuenote",
            name="weighbridge_weight_13",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True, verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="goodsissuenote",
            name="weighbridge_weight_14",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True, verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="goodsissuenote",
            name="weighbridge_weight_15",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True, verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="goodsissuenote",
            name="weighbridge_weight_2",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True, verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="goodsissuenote",
            name="weighbridge_weight_3",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True, verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="goodsissuenote",
            name="weighbridge_weight_4",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True, verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="goodsissuenote",
            name="weighbridge_weight_5",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True, verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="goodsissuenote",
            name="weighbridge_weight_6",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True, verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="goodsissuenote",
            name="weighbridge_weight_7",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True, verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="goodsissuenote",
            name="weighbridge_weight_8",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True, verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="goodsissuenote",
            name="weighbridge_weight_9",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True, verbose_name=""
            ),
        ),
    ]
