# Generated by Django 2.2.5 on 2022-01-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='authentication',
            field=models.CharField(default='0', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(default='1', max_length=7, null=True),
        ),
    ]
