# Generated by Django 2.2.5 on 2022-01-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220120_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='support.user2@kapa-oil.local', max_length=254),
        ),
    ]
