# Generated by Django 3.2.14 on 2022-11-05 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0078_rename_department_to1_goods_issue_note_department_to'),
        ('users', '0008_remove_profile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='waste_management.department'),
        ),
    ]
