# Generated by Django 3.2.14 on 2022-11-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user']},
        ),
    ]
