# Generated by Django 2.2.5 on 2021-10-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_bpinspectionform'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpinspectionform',
            name='boolean',
            field=models.BooleanField(default=False, verbose_name='New Inspection Form'),
        ),
    ]
