# Generated by Django 2.2.5 on 2021-11-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20211112_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtsform',
            name='material_description',
            field=models.CharField(max_length=40, verbose_name='Material description'),
        ),
    ]
