# Generated by Django 2.2.5 on 2021-11-30 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_auto_20211130_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='rtsform',
            name='reason_for_rejection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.Reason', verbose_name='Reason for rejection'),
        ),
    ]
