# Generated by Django 2.2.5 on 2021-12-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0018_rtsform_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtsform',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='rts_pics', verbose_name='Picture'),
        ),
    ]
