# Generated by Django 2.2.5 on 2021-12-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0023_auto_20211228_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtsform',
            name='fm_comment',
            field=models.CharField(blank=True, choices=[('G', 'Good'), ('L', 'Leaking')], max_length=100, null=True, verbose_name='Resolution'),
        ),
    ]
