# Generated by Django 2.2.5 on 2022-01-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0024_auto_20211228_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtsform',
            name='fm_comment',
            field=models.CharField(blank=True, choices=[('Reject full delivery', 'Reject full delivery'), ('Reject affected quantity', 'Reject affected quantity'), ('Offload delivery and segregate', 'Offload delivery and segregate'), ('Accept delivery as is', 'Accept delivery as is')], max_length=100, null=True, verbose_name='Resolution'),
        ),
    ]
