# Generated by Django 2.2.5 on 2022-04-06 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0033_auto_20220204_1557'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BPinspectionform',
        ),
        migrations.DeleteModel(
            name='Presentation',
        ),
        migrations.DeleteModel(
            name='Speaker',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
