# Generated by Django 2.2.5 on 2022-05-04 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('material_code', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='RTSform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('department', models.CharField(default='Warehouse', max_length=20)),
                ('vehicle_number', models.CharField(max_length=40, verbose_name='Vehicle Number')),
                ('dnote_number', models.CharField(max_length=40, verbose_name='D/Note number')),
                ('dnote_date', models.CharField(max_length=40, verbose_name='D/Note Date')),
                ('quality_issue', models.CharField(max_length=100, verbose_name='Quality issue')),
                ('delivery_quantity', models.IntegerField(verbose_name='Delivery quantity')),
                ('sampled_quantity', models.IntegerField(verbose_name='Sampled quantity')),
                ('quantity_affected', models.IntegerField(verbose_name='Quantity affected')),
                ('acceptable_level', models.CharField(max_length=40, verbose_name='Acceptable level')),
                ('batches_sampled', models.CharField(max_length=40, verbose_name='Batches sampled')),
                ('mould', models.CharField(max_length=40, verbose_name='Mould')),
                ('hod_comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='HOD comment')),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='rts_pics', verbose_name='Picture')),
                ('form_status', models.IntegerField(default='0', null=True)),
                ('qao_comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='QAO comment')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('material_description', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rts_forms.Material', verbose_name='Material description')),
                ('reason_for_rejection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rts_forms.Reason', verbose_name='Reason for rejection')),
                ('resolution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rts_forms.Resolution')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rts_forms.Supplier')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
