# Generated by Django 2.2.5 on 2021-10-25 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BPinspectionform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('serial_number', models.CharField(max_length=40)),
                ('sample1', models.CharField(max_length=40)),
                ('sample2', models.CharField(max_length=40)),
                ('sample3', models.CharField(max_length=40)),
                ('sample4', models.CharField(max_length=40)),
                ('sample5', models.CharField(max_length=40)),
                ('S1Sealing', models.CharField(choices=[('G', 'Good'), ('L', 'Leaking')], max_length=40)),
                ('S2Sealing', models.CharField(choices=[('G', 'Good'), ('L', 'Leaking')], max_length=40)),
                ('S3Sealing', models.CharField(choices=[('G', 'Good'), ('L', 'Leaking')], max_length=40)),
                ('S4Sealing', models.CharField(choices=[('G', 'Good'), ('L', 'Leaking')], max_length=40)),
                ('S5Sealing', models.CharField(choices=[('G', 'Good'), ('L', 'Leaking')], max_length=40)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
