# Generated by Django 2.2.5 on 2022-05-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rts_forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_code',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
