# Generated by Django 2.2.5 on 2022-05-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rts_forms', '0002_supplier_supplier_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtsform',
            name='dnote_date',
            field=models.DateField(verbose_name='D/Note Date'),
        ),
    ]
