# Generated by Django 2.2.5 on 2022-08-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rts_forms', '0003_auto_20220511_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='material',
            name='uom',
            field=models.CharField(blank=True, default='PC', max_length=20, null=True, verbose_name='UOM'),
        ),
    ]
