# Generated by Django 3.2.14 on 2022-10-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rts_forms', '0004_auto_20220831_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtsform',
            name='delivery_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Delivery quantity'),
        ),
        migrations.AlterField(
            model_name='rtsform',
            name='quantity_affected',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Quantity affected'),
        ),
        migrations.AlterField(
            model_name='rtsform',
            name='sampled_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Sampled quantity'),
        ),
    ]
