# Generated by Django 2.2.5 on 2021-11-12 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtsform',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.Department'),
        ),
    ]
