# Generated by Django 3.2.14 on 2022-10-04 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rts_forms', '0006_rtsform_department_internal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtsform',
            name='department_internal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Department_Affected', to='rts_forms.department'),
        ),
    ]
