# Generated by Django 2.2.5 on 2021-11-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_auto_20211126_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtsform',
            name='quality_issue',
            field=models.CharField(max_length=40, verbose_name='Quality issue'),
        ),
    ]
