# Generated by Django 4.1.3 on 2023-04-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rts_forms", "0008_supplier_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="email",
        ),
        migrations.AddField(
            model_name="supplier",
            name="email",
            field=models.ManyToManyField(to="rts_forms.emailaddress"),
        ),
    ]
