# Generated by Django 2.2.5 on 2021-11-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_auto_20211126_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtsform',
            name='acceptable_level',
            field=models.CharField(max_length=40, verbose_name='AL'),
        ),
        migrations.AlterField(
            model_name='rtsform',
            name='batches_sampled',
            field=models.CharField(max_length=40, verbose_name='BS'),
        ),
        migrations.AlterField(
            model_name='rtsform',
            name='quantity_affected',
            field=models.CharField(max_length=40, verbose_name='QA'),
        ),
        migrations.AlterField(
            model_name='rtsform',
            name='sampled_quantity',
            field=models.CharField(max_length=40, verbose_name='SQ'),
        ),
    ]
