# Generated by Django 2.2.5 on 2021-11-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_auto_20211126_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtsform',
            name='acceptable_level',
            field=models.CharField(max_length=40, verbose_name='Acceptable level'),
        ),
        migrations.AlterField(
            model_name='rtsform',
            name='batches_sampled',
            field=models.CharField(max_length=40, verbose_name='Batches sampled'),
        ),
        migrations.AlterField(
            model_name='rtsform',
            name='quantity_affected',
            field=models.CharField(max_length=40, verbose_name='Quantity affected'),
        ),
        migrations.AlterField(
            model_name='rtsform',
            name='sampled_quantity',
            field=models.CharField(max_length=40, verbose_name='Sampled quantity'),
        ),
    ]
