# Generated by Django 2.2.5 on 2021-11-30 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_auto_20211126_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('material_code', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='rtsform',
            name='material_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.Material', verbose_name='Material description'),
        ),
    ]
