# Generated by Django 2.2.5 on 2021-12-20 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_rtsform_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rtsform',
            name='serial_number',
        ),
    ]
