# Generated by Django 2.2.5 on 2021-12-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0020_auto_20211220_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtsform',
            name='form_status',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
