# Generated by Django 2.2.5 on 2021-12-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0021_auto_20211222_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtsform',
            name='qao_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
