# Generated by Django 2.2.5 on 2022-01-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0025_auto_20220119_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtsform',
            name='department',
            field=models.CharField(default='Warehouse', max_length=20),
        ),
    ]
