# Generated by Django 2.2.5 on 2022-02-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0030_rtsform_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolution',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
