# Generated by Django 2.2.5 on 2022-02-04 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0031_auto_20220204_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtsform',
            name='resolution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='forms.Resolution'),
            preserve_default=False,
        ),
    ]
