# Generated by Django 2.2.5 on 2022-02-04 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0032_auto_20220204_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtsform',
            name='resolution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.Resolution'),
        ),
    ]
