# Generated by Django 2.2.5 on 2022-04-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0035_auto_20220406_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtsform',
            name='quantity_affected',
            field=models.IntegerField(verbose_name='Quantity affected'),
        ),
        migrations.AlterField(
            model_name='rtsform',
            name='sampled_quantity',
            field=models.IntegerField(verbose_name='Sampled quantity'),
        ),
    ]
